# Generated by Django 2.2.2 on 2019-07-31 06:49

from django.db import migrations, models
import sample1.demo


class Migration(migrations.Migration):

    dependencies = [
        ('sample1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='even_field',
            field=models.IntegerField(default=2, validators=[sample1.demo.validate_even]),
            preserve_default=False,
        ),
    ]
